### ISSUE TITLE
更新到最新版本后，dashboard不能隐藏bufferline的显示

### ISSUE THREAD

**Issue by HUAHUAI23** [glepnir/dashboard-nvim#249]
这是 更新前的版本，没有hyper前的版本
![image](https://user-images.githubusercontent.com/43649186/214840505-bcfcf691-0bd9-4635-bdbf-a6f4c2457eec.png)

这是更新后的版本，顶部没有隐藏bufferline 
![image](https://user-images.githubusercontent.com/43649186/214840548-ef406c8e-4b64-4acc-a0c6-4bea72d3164a.png)

**Comment by glepnir** [comment]
`set showtabline?` 输出是什么

**Comment by HUAHUAI23** [comment]
`showtabline=0`
![image](https://user-images.githubusercontent.com/43649186/214841346-83dec650-70f0-4228-b22d-7f70ff2e5b69.png)

**Comment by glepnir** [comment]
0的时候是没有tabline的。

**Comment by HUAHUAI23** [comment]
我把这个选项设置 0 就不会展示那个 tabline吧

**Comment by fecet** [comment]
借这问一下, api有什么改动吗, 我怎么一更新不显示dashboard了

**Comment by glepnir** [comment]
你更新下试试？

**Comment by glepnir** [comment]
你更新下试试？

**Comment by HUAHUAI23** [comment]
好像还是不行
我设置了这个等于0 咋还是2 难道bufferline 重写了这个，我试试在buffline加载后设置这个
![image](https://user-images.githubusercontent.com/43649186/214843378-37a87df4-b090-490e-b244-af939134d6d7.png)
![image](https://user-images.githubusercontent.com/43649186/214843389-956109a0-87bd-4742-907d-8e56134bd8e0.png)

**Comment by glepnir** [comment]
bufline 会重写这个值。 你在更新一下。我把这个设置延后了。看能不能解决吧。

**Comment by HUAHUAI23** [comment]
可以了 是bufferline重设置了 这个showtabline
![image](https://user-images.githubusercontent.com/43649186/214843705-1cb02f43-a136-4e86-b1a2-f5d2104a384c.png)

**Comment by Flo-Slv** [comment]
Hey !

Can you translate ? I have an issue with showtabline too...

**Comment by glepnir** [comment]
did you update to latest version ? I think it should be fixed.

**Comment by HUAHUAI23** [comment]
yes, the latest version fix this

**Comment by Flo-Slv** [comment]
> did you update to latest version ? I think it should be fixed.

I updated to latest version and add this to my neovim config.

`showtabline = 2`

It's seems working now without issue !

**Comment by Flo-Slv** [comment]
Okey I am still having the issue as you can on the screenshot.

![Screenshot from 2023-01-26 14-30-23](https://user-images.githubusercontent.com/11678456/214847916-2f153a6f-9ebe-4f49-87d3-b22d44f6738e.png)

**Comment by HUAHUAI23** [comment]
don't need add `showtabline =2`, my problem caused by [bufferline](https://github.com/akinsho/bufferline.nvim), it will override showtabline value to 2, and the 1 is don't show tabline, the latest dashboard.nvm have fixed it

**Comment by Flo-Slv** [comment]
> don't need add `showtabline =2`, my problem caused by [bufferline](https://github.com/akinsho/bufferline.nvim), it will override showtabline value to 2, and the 1 is don't show tabline, the latest dashboard.nvm have fixed it

I am still having the issue. Even if I don't set showtabline. By default showtabline is set to 0. Is there a workaround to avoid this issue ? Because even with last version of Dashboard, error appears. Sorry to borrow you !

**Comment by HUAHUAI23** [comment]
can you take a screeshot

**Comment by Flo-Slv** [comment]
Screenshot above.

Same error with setting `showtabline = 2` and no setting showtabline.

**Comment by glepnir** [comment]
please update @Flo-Slv  the pos of you pic not have code . I think your version is old

**Comment by Flo-Slv** [comment]
I already updated. 

Neovim version:
```sh
╰─ nvim --version
NVIM v0.9.0-dev-823+g41aa5ce3e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/home/floslv/Flo/Apps/Neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/floslv/Flo/Apps/Neovim/.deps/usr/include -I/home/floslv/Flo/Apps/Neovim/build/src/nvim/auto -I/home/floslv/Flo/Apps/Neovim/build/include -I/home/floslv/Flo/Apps/Neovim/build/cmake.config -I/home/floslv/Flo/Apps/Neovim/src
Compiled by floslv@FloSlv

Features: +acl +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

![packer](https://user-images.githubusercontent.com/11678456/214850153-434f65ce-6e4a-4c44-86bb-fdafb4a11772.png)

![packer 2](https://user-images.githubusercontent.com/11678456/214850164-f3c66d07-1dc0-4386-a34e-07a300ab073d.png)

**Comment by glepnir** [comment]
sorry my network is crashed. update now.

**Comment by HUAHUAI23** [comment]
@glepnir 大兄弟 我有点困了， 准备去睡了🤣 新年快乐 恭喜发财

**Comment by glepnir** [comment]
@Flo-Slv  can you test it now ?

**Comment by Flo-Slv** [comment]
> sorry my network is crashed. update now.

Okey, I just updated, and it seems working like a charm now !

Btw, I found a typo in the README.md

Missing one ',' after `end` (when closing function).

```sh
use {
  'glepnir/dashboard-nvim',
  event = 'VimEnter',
  config = function()
    require('dashboard').setup {
      -- config
    }
  end
  require = { {'nvim-tree/nvim-web-devicons'}}
}
```

**Comment by Flo-Slv** [comment]
> @glepnir 大兄弟 我有点困了， 准备去睡了rofl 新年快乐 恭喜发财

Have a good night, cheers from France !

**Comment by glepnir** [comment]
glad to hear that :)

**Comment by Flo-Slv** [comment]
Last one and you can go sleep !

Typo in README.md for Lazy.nvim.
It should be `dependencies` and not `dependices`.

```sh
{
  'glepnir/dashboard-nvim',
  event = 'VimEnter',
  opts = {
    -- config
  },
  dependices = { {'nvim-tree/nvim-web-devicons'}}
}
```

Have a good one, and thanks for this amazing plugin !

**Comment by glepnir** [comment]
go sleep is  not me :)  still have some neovim core code need write . fixed.
